### ISSUE TITLE
连接成功后，如何获取本地所使用的地址与端口

### ISSUE THREAD

**Issue by fjfzeagle** [winddriver/Delphi-Cross-Socket#1]
FClientSocket.Connect('127.10.10.1',7000,
    procedure(aSocketHandle: THandle;ASuccess: Boolean)
    begin
      TThread.Synchronize(nil,
        procedure
        begin
          if ASuccess then
            ShowMessage('Connect SUCCESS!! aSocketHandle:' + aSocketHandle.ToString)
          else
            ShowMessage('Connect FAILED!!aSocketHandle:' + aSocketHandle.ToString);
        end);
      end);
连接服务端成功后，
procedure TBaseSocket.TriggerConnected(AConnection: ICrossConnection);
begin
  inherited;
  PrintLog((Format('Connected:PeerAddr:%s;PeerPort:%d;ConnectType:%s;socket:%d',[AConnection.PeerAddr,
      AConnection.PeerPort,
      GetEnumName(TypeInfo(TConnectType),Ord(AConnection.ConnectType)),
      AConnection.Socket])));
end;
以后事件的打印结果：
Connected:PeerAddr:127.10.10.1;PeerPort:7000;ConnectType:ctConnect;socket:820

如果获取LocalAddr与LocalPort（从服务端连接事件可以看到本地连接所使用的端口是4930）？

**Comment by winddriver** [comment]
我更新了一下，给回调函数增加了Socket句柄，并且增加了一个GetConnection方法，现在你可以这样
`    FClientSocket.Connect('127.0.0.1', 7000,
      procedure(ASocket: THandle; ASuccess: Boolean)
      var
        LConnection: ICrossConnection;
      begin
        if ASuccess then
        begin
          FSocket.LockConnections;
          try
            LConnection := FSocket.GetConnection(ASocket);
          finally
            FSocket.UnlockConnections;
          end;

          // 这里你可以使用 LConnection 做你想做的事了
        end;
      end);
`

**Comment by fjfzeagle** [comment]
很好，非常感谢！
