### ISSUE TITLE
建议增加SO_REUSEPORT，SO_REUSEADDR在linux下多开进程是无效的

### ISSUE THREAD

**Issue by pony5551** [winddriver/Delphi-Cross-Socket#100]
class function TSocketAPI.SetReUsePort(const ASocket: THandle;
  const AReReUsePort: Boolean): Integer;
const
  SO_REUSEPORT = 15;
var
  LOptVal: Integer;
begin
  if AReReUsePort then
    LOptVal := 1
  else
    LOptVal := 0;
  Result := TSocketAPI.SetSockOpt(ASocket, SOL_SOCKET, SO_REUSEPORT, LOptVal, SizeOf(Integer));
end;

**Comment by winddriver** [comment]
抱歉，现在才改，已经更新了
