### ISSUE TITLE
CrossHttpConsole 接收 POST 大文件(>2GB)数据， 0D0A 会变为 0D0A0A

### ISSUE THREAD

**Issue by frankwu-delphi** [winddriver/Delphi-Cross-Socket#110]
用自带的Demos\CrossHttpConsole测试，具体表现：
edge 浏览器 POST 来的文件数据，会在数据有 **0D0A** 的地方加多一个 **0A**，变为 **0D0A0A** 

![18](https://user-images.githubusercontent.com/54831748/199149000-78ac014e-91b8-4f95-840d-a2a8111423d1.png)

[附件是测试代码，编译后运行，在edge浏览器中输入：](http://127.0.0.1:8000/upload)，
上传一个超过2G大小的文件，用 HEX工具打开并与源文件比较，会发现多出的字节数；
[CrossHttpConsole.zip](https://github.com/winddriver/Delphi-Cross-Socket/files/9906383/CrossHttpConsole.zip)

**Comment by winddriver** [comment]
感谢反馈，已确认该bug，并已修正
