### ISSUE TITLE
大神，您提交新代码以后，部分类带有OVERRIDE的构造函数，都失效了

### ISSUE THREAD

**Issue by hist008** [winddriver/Delphi-Cross-Socket#111]
TCrossServerConnection：（不止这一个类，就那这个类做提示把）  

  constructor Create(const AOwner: ICrossSocket; const AClientSocket: THandle;
      const AConnectType: TConnectType); override;

AOwner是否应该是TCrossSocketBase呢?
请大神给与指示

**Comment by winddriver** [comment]
对，修改AOwner类型即可

发自我的 iPhone

在 2023年3月15日，14:07，hist008 ***@***.***> 写道：

﻿

TCrossServerConnection：（不止这一个类，就那这个类做提示把）

constructor Create(const AOwner: ICrossSocket; const AClientSocket: THandle;
const AConnectType: TConnectType); override;

AOwner是否应该是TCrossSocketBase呢?
请大神给与指示
