### ISSUE TITLE
WebSocket Server中如何开启压缩功能？以及发送Ping控制帧？

### ISSUE THREAD

**Issue by bagualing** [winddriver/Delphi-Cross-Socket#112]
我试了设置TNetCrossWebSocketServer里的压缩启用与最小压缩阀值，但在WebSocket数据传输时并没有压缩数据。

另外如何主动发Ping包呢？

**Comment by winddriver** [comment]
目前压缩只支持http，不支持websocket
主动发Ping包这个目前也没有，我这边暂时没有发现这样的使用场景

**Comment by bagualing** [comment]
> 

谢谢。
再多问一下，目前支持path么？类似ws://host:port/path这种带path的。没找到如何实现。

**Comment by winddriver** [comment]
手动发送ping包比较简单，我顺便改了
path当然是支持的，你直接用就是了，比如客户端那边连接 ws://host:port/path123，你服务端收到的websocket相关事件里connection.Requet.Path就是path123

**Comment by bagualing** [comment]
太棒了！
