### ISSUE TITLE
httpclient连接自签名服务器失败

### ISSUE THREAD

**Issue by windflee** [winddriver/Delphi-Cross-Socket#114]
httpclient不能连接自签名的服务器，可否添加一个忽略证书检查的属性了？类似于自带的TNetHTTPclient组件，都有OnValidateServerCertificate之类的事件可以忽略服务器证书检查的。

**Comment by winddriver** [comment]
肯定是支持自签名证书的，demo里带的证书就是我自己生成的，你检查下你的证书是不是老版本openssl生成的，需要用openssl 1.1以上的版本生成证书，Tools目录里带了OpenSSL 3

源代码里(Net.CrossSslSocket.OpenSSL.pas)这一行就是用来支持自签名证书的
SSL_CTX_set_verify(FSslCtx, SSL_VERIFY_NONE, nil);

**Comment by windflee** [comment]
确实是。
