### ISSUE TITLE
linux下进行百万请求压测过段时间请求就会无响应

### ISSUE THREAD

**Issue by fjfzeagle** [winddriver/Delphi-Cross-Socket#115]
cpu个数我指定为0，不使用ssl：__HttpServer := TCrossHttpServer.Create(0, false);  
压测指令：bombardier.exe -c 100 -n 1000000 http://192.168.5.156:8080/
压一段时间后，程序就卡住无法响应了，压个10万没问题，压到100万个请求就会无响应，再用浏览器打开http://192.168.5.156:8080/，一直无法响应，强制停止压测，浏览器也无法再打开了
bombardier下载地址：https://github.com/codesenberg/bombardier

**Comment by fjfzeagle** [comment]
对了，我使用的是FPC3.3.1+lararus3.99

**Comment by winddriver** [comment]
估计是出现某种异常了，能否提供你运行的Linux具体信息？还有CPU是什么指令集，x64、aarch64、龙芯？
我需要相关信息好尽量还原运行环境去追查

**Comment by winddriver** [comment]
无语了，查了下，居然是demo里Get回调使用了一个外部的字符串变量，每次都在给该变量重新赋值，导致多线程下同时对该字符串写入出现访问异常，已经修正

**Comment by fjfzeagle** [comment]
大侠辛苦了！
