### ISSUE TITLE
websocket 提交长字符串的时候，服务方没有反应，但是提交短字符串的时候，没有问题，使用其他控件长字符串没问题。

### ISSUE THREAD

**Issue by wqmeng** [winddriver/Delphi-Cross-Socket#117]
websocket 提交长字符串的时候，服务方没有反应，但是提交短字符串的时候，没有问题，使用其他控件长字符串没问题。

如果需要可以私信联系方式，我会提供一个测试应用。

**Comment by winddriver** [comment]
可以将完整的测试工程源码发到我email: soulawing@gmail.com
