### ISSUE TITLE
WebSocketClient连接C#的WebSocket生成Key有问题

### ISSUE THREAD

**Issue by Leewx820** [winddriver/Delphi-Cross-Socket#118]
![image](https://github.com/winddriver/Delphi-Cross-Socket/assets/26474036/9ece57b4-08ae-41b0-a74d-b37fdebdff5e)
这个地方内部调用生成了长度为32的字符串,导致连接C#的WebSocket服务无法成功,改成16位长度就可以了,这个是啥原因呢

**Comment by winddriver** [comment]
感谢反馈，我查询了WebSocket的RFC协议描述，Sec-WebSocket-Key的确应该只有16个字节，已经修正
