### ISSUE TITLE
WebSocketServer例子编译不了

### ISSUE THREAD

**Issue by fjfzeagle** [winddriver/Delphi-Cross-Socket#120]
procedure TCrossHttpResponse.Send(const ABody: TBytes;
  const AOffset, ACount: NativeInt; const ACallback: TCrossConnectionCallback);
var
  LBody: TBytes;
  LOffset, LCount: NativeInt;
begin
  // 增加其引用计数
  LBody := ABody;

  LOffset := AOffset;
  LCount := ACount;
  TCrossHttpUtils.AdjustOffsetCount(Length(ABody), LOffset, LCount);
  .....

报错
[dcc64 Error] Net.CrossHttpServer.pas(4093): E2250 There is no overloaded version of 'AdjustOffsetCount' that can be called with these arguments

**Comment by winddriver** [comment]
已修正
