### ISSUE TITLE
调试WebSocket时发现一出内存泄漏

### ISSUE THREAD

**Issue by Leewx820** [winddriver/Delphi-Cross-Socket#121]
![image](https://github.com/winddriver/Delphi-Cross-Socket/assets/26474036/d8da52d7-5e9b-46fd-94ca-09cbb4e44651)
![image](https://github.com/winddriver/Delphi-Cross-Socket/assets/26474036/04680351-c226-4c93-82b7-d81b4fb4eb97)

使用 Demos\Delphi\WebSocketClient\ 可重现

**Comment by winddriver** [comment]
这个问题早就修正了
发自我的 iPhone

在 2024年1月5日，16:10，Leewx820 ***@***.***> 写道：

﻿

image.png (view on web)<https://github.com/winddriver/Delphi-Cross-Socket/assets/26474036/d8da52d7-5e9b-46fd-94ca-09cbb4e44651>
image.png (view on web)<https://github.com/winddriver/Delphi-Cross-Socket/assets/26474036/04680351-c226-4c93-82b7-d81b4fb4eb97>

使用 Demos\Delphi\WebSocketClient\ 可重现

**Comment by Leewx820** [comment]
好的,可能是我没拉最新代码,我拉一下最新的
