### ISSUE TITLE
ios下仍然报错

### ISSUE THREAD

**Issue by windflee** [winddriver/Delphi-Cross-Socket#127]
用最新的代码，在D12 + ios17.2 下编译websocketclient的DEMO，仍然报错：
[DCC Error] Net.OpenSSL.pas(601): E2168 Field or method identifier expected

**Comment by windflee** [comment]
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(601,50): error E2168: E2168 Field or method identifier expected
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(601,64): error E2168: E2168 Field or method identifier expected
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(604,48): error E2168: E2168 Field or method identifier expected
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(604,61): error E2168: E2168 Field or method identifier expected
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(607,54): error E2168: E2168 Field or method identifier expected
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(607,70): error E2168: E2168 Field or method identifier expected
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(845,13): error E2003: E2003 Undeclared identifier: 'FSslVersion'
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(979,7): error E2003: E2003 Undeclared identifier: 'FSslLibHandle'
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(979,30): error E2003: E2003 Undeclared identifier: 'FCryptoLibHandle'
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(983,5): error E2034: E2034 Too many actual parameters
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(984,5): error E2034: E2034 Too many actual parameters
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(994,3): error E2003: E2003 Undeclared identifier: 'FSslVersion'
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(999,7): error E2003: E2003 Undeclared identifier: 'FSslLibHandle'
D:\controls\Delphi-Cross-Socket-master\Net\Net.OpenSSL.pas(999,30): error E2003: E2003 Undeclared identifier: 'FCryptoLibHandle'
D:\controls\Delphi-Cross-Socket-master\Net\Net.CrossSslSocket.OpenSSL.pas(85,2): error F2063: F2063 Could not compile used unit 'Net.OpenSSL.pas'

**Comment by winddriver** [comment]
已修正
