### ISSUE TITLE
ICrossServer开启SSL后一个奇怪的问题

### ISSUE THREAD

**Issue by wuhao13** [winddriver/Delphi-Cross-Socket#129]
在SSL不启用的情况下，Client向server多连接同时发送代码并没有出现奇怪的问题
`    for I := 0 to 100 do
    begin
      con.Connect('127.0.0.1',999,
         procedure(const AConnection: ICrossConnection; const ASuccess: Boolean)
          var
            c: Integer;
         begin
          if AConnection.ConnectStatus = csConnected then
            begin
              for c := 1 to 200 do
                AConnection.SendBuf(sa,packsize);
            end
          else
          begin
            Log.Info('连接未完成')
          end;
         end
      );
    end;`
但是启用了SSL后，上述代码服务端疯狂报SSL_read error 1 error:00000001:lib(0)::reason(1)，并且粘包出现混乱，调试未找到原因，请指导。

**Comment by winddriver** [comment]
因为SendBuf是异步的，你当成同步方法在用

开启ssl后，实际发出的数据是需要经过ssl重新加密包装的，你一次调用的数据包很有可能会被拆分成多次发送，你连续多次异步调用必然会导致数据包混乱

**Comment by wuhao13** [comment]
> 因为SendBuf是异步的，你当成同步方法在用
> 
> 开启ssl后，实际发出的数据是需要经过ssl重新加密包装的，你一次调用的数据包很有可能会被拆分成多次发送，你连续多次异步调用必然会导致数据包混乱

我修改了一下，使用TEvent将发包变成了阻塞，似乎在单链接没有任何问题，同时多个connect依旧会出现莫名其妙的包错乱，这就非常奇怪，难道SSL所有链接是共享一个收发缓冲区么？这好像很出乎我的意料。

**Comment by winddriver** [comment]
把完整的测试工程源码打包发上来，我找时间看看

**Comment by wuhao13** [comment]
> 把完整的测试工程源码打包发上来，我找时间看看

发您soulawing@gmail.com这个邮箱了

**Comment by wuhao13** [comment]
我最近有点犯傻，写代码没带脑子，感谢作者指导！
