### ISSUE TITLE
Linux - 'eventfd' cannot be used in inline function

### ISSUE THREAD

**Issue by havrlisan** [winddriver/Delphi-Cross-Socket#135]
When compiling for Linux, I get the following error:

> [DCC Error] Net.CrossSocket.Epoll.pas(598): E2441 Inline function declared in interface section must not use local symbol 'eventfd'

The inline function is `TEpollCrossSocket._OpenStopHandle`.

**Comment by winddriver** [comment]
Thanks for the feedback, it has been fixed.
