### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by wr960204** [winddriver/Delphi-Cross-Socket#137]
get/post/all...
这类方法能否增加一种重载，比如：
function Get(const APath: array of string; const ARouterProc: TCrossHttpRouterProc): ICrossHttpServer; overload;
否则多个路径共用一个方法，要反复地写get方法，用这种重载一次可以指定多个路径匹配一个路由回调函数。

**Comment by winddriver** [comment]
路径其实支持正则表达式，你要多个路径共用一个方法这样写就可以了

Get('/Path1|/Path2|/Path3', ...)

**Comment by wr960204** [comment]
正则处理是不有问题。
.Get('/json|/queryjson|/queryip|/query'。。。。。。
.Get('/str|/querystr/'。。。。。。
结果/querystr匹配到第一个里面去了
