### ISSUE TITLE
WebSocketClient Mask 掩码应该如何使用。

### ISSUE THREAD

**Issue by nilnil2023** [winddriver/Delphi-Cross-Socket#138]
TCrossWebSocketParser.MakeFrameData(AOpCode, AFin, 1, AData, ACount)；AMaskKey设置为1后会导致服务端接收到的封包错误。

**Comment by winddriver** [comment]
感谢反馈，该问题已修正
顺便增加了MaskingKey属性

**Comment by nilnil2023** [comment]
测试了，好用！is good !
