### ISSUE TITLE
Win64 HTTP的例子 运行期报错

### ISSUE THREAD

**Issue by ugksoft** [winddriver/Delphi-Cross-Socket#16]
constructor TCrossHttpServer.Create(AIoThreads: Integer);
var
  I: Integer;
begin
  inherited Create(AIoThreads);  在Win64时,  这行运行期,内部报错, 我没细看原因,你有空看看,

**Comment by winddriver** [comment]
测试了下Win64完全正常
![20180304075507](https://user-images.githubusercontent.com/3221597/36940620-8400cd6e-1f81-11e8-8def-fbdb4079f0cc.png)

**Comment by ugksoft** [comment]
我是Win7,旗舰,cn_windows_7_ultimate_with_sp1_x64_dvd_u_677408.iso的系统

调试报错,后面如果我有找到原因,告诉你
