### ISSUE TITLE
希望作者,提供一下并发量,并发新连接等经验

### ISSUE THREAD

**Issue by ugksoft** [winddriver/Delphi-Cross-Socket#17]
1.需要多少硬件配置/带宽,内存,你的测试环境是如何的,双机什么配置,
    专业交换机,/普通IT用户的无线路由器/最垃圾的电脑白丁家路由器

2.现实生产环境,BAT这流氓家服务器质量,大概到什么浏览,需要什么配置

3.同时在线多少人,需要多少内存
   我测试32位程序时,20万连接,需要200M内存,包括进程自己需要的内存,Win7平台
4.每秒发起多少连接时,需要什么样的硬件配置,现实环境,速度是如何, 其它有什么产品有更高并发,如何提升
  我测试下来,不管Win还是Linux,新建连接数,都只有每秒1000-2000(1000M,OpenWrt路由,双i7, Win7 64bit)
  (本机IP或回路,每秒新建连接大概7K-1W)
5.每秒IO次数,如何优化
  我每秒IO量(1Byte-1KByte一包),和新连接数速度,差不多,实在寒酸,基本用户都不可能满足,更不要说DDOS
6.一些测试工具推荐,瓶颈查找方法或工具等

以上是我自己遇到的情况, 用你的TestCrossSocket/CrossHttpConsole(非SSL) , 
  AB,和自己写的socket多线程,异步并发程序测试得出结果

**Comment by winddriver** [comment]
TCP连接的建立需要3次握手，也就是说纯粹只是做连接，中间其实也是有数据交互的，连接的建立其实是非常耗时的，把这个过程放到外网上面，中间会经过无数的路由、交换机，整个过程就更漫长了。

你可以看看这篇文章：
  理解socket connect和accept的实现细节
写得比较清晰

你用单台客户端做连接速度的测试，所以你得出的结果其实是你单机每秒能往外连接的数量，服务器那边其实还能处理更多连接。

这个测试环境的确不好弄，要测试出服务器比较准确的每秒连接数，最好能使用大量物理客户机去连接。

你可以试试租用几十台阿里的云服务器来做测试，按天租，费用并不高。

**Comment by ugksoft** [comment]
可能我没说清楚,

我内网双机测试,中间经过一个路由

C/S都用你的程序测试下来, 并发新连接,只有1000-2000左右,实在大出我意料,
我还特意写了个客户端,异步连接,100个线程,每个线程100个sockets.tcpclient,异步(noBlocking)去连接, 连接数,上升速度,目视,也只有1000-2000左右, 
连接,阿里的2M带宽的机子(Win2008), 并发 新连接只有200左右,  只连接,实际负载数据一个字节都不发

i7 Win的宿主机,  开两个系统,这两个系统之间连,也只有这么点


sockets的连接情况,我是知道的, 97年,就啃过 "TCP/IP详解卷1" 英文,电子版,当年只啃了TCPIP部分,后面协议部分啃了点点,没啃下去
老人了,一直做算法为主,一直没有做过什么大的网络应用, 测试下来,才这么点,太意外了,才发你邮件问细节

根据我抓包情况
 实际连接,带宽还是比较浪费的,    以下是路由器上的情况,   电信计算费卡带宽是在接入这头,  所以不能按互联网上的IP包头计算法来算带宽浪费

**以下数据,不保证人人都一样,仅仅我抓包的情况**

基础数据大小, 信号类型
82    SYN
82    SYN,ACK
74    PSH,ACK  PUSH 发送数据 有时基础数据是 82
74    ACK 应答
86    Dup,ACK,
74    FIN,ACK(这个会重复几次确认)   如果强制发送62 RST,ACL关闭连接, 能够省点掉几次来回确认的带宽

这是我在OpenWrt路由器上用tcpdump抓数据分析的, 因为adsl,里面有6个字节PPPOE数据, 头上有本机MAC,和电信MAC(可能是光猫) 浪费了12Byte
不排除,光猫到电信交换机,带宽卡壳点之间,还有其它什么数据浪费

所以,实际 通讯中, 短连接,太浪费基础包,如果每次发16,32Byte之类小包  实际带宽利用率,可能只有 1/100了
应该选择,长连接, 不发数据的话,除了很长时间的Keep包就不会有带宽浪费 (Keep包默认2小时一次, ,网上他们一般改短到20-30分钟一次)

在不重要数据,比如报告客户端是否打开之类的不是特别重要的数据,又不是需要密集发送的,容忍丢包的 可考虑UDP
UDP大小是
50+实体数据, 抓包发现,有时会多点填充的0 比如发8个byte,实际他可能发了16个byte,尾巴上有多出几个0来

**Comment by winddriver** [comment]
你可以在同样的环境下，换其它服务程序测试一下看看，比如nodejs、ngnix、lighthttpd，这几个是目前应用很广，性能也非常出色的服务程序。

发自我的 iPhone

在 2018年3月4日，23:13，ugksoft <notifications@github.com<mailto:notifications@github.com>> 写道：


可能我没说清楚,

我内网双机测试,中间经过一个路由

C/S都用你的程序测试下来, 并发新连接,只有1000-2000左右,实在大出我意料,
我还特意写了个客户端,异步连接,100个线程,每个线程100个sockets.tcpclient,异步(noBlocking)去连接, 连接数,上升速度,目视,也只有1000-2000左右,
连接,阿里的2M带宽的机子(Win2008), 并发 新连接只有200左右, 只连接,实际负载数据一个字节都不发

i7 Win的宿主机, 开两个系统,这两个系统之间连,也只有这么点

sockets的连接情况,我是知道的, 97年,就啃过 "TCP/IP详解卷1" 英文,电子版,当年只啃了TCPIP部分,后面协议部分啃了点点,没啃下去
老人了,一直做算法为主,一直没有做过什么大的网络应用, 测试下来,才这么点,太意外了,才发你邮件问细节

根据我抓包情况
实际连接,带宽还是比较浪费的, 以下是路由器上的情况, 电信计算费卡带宽是在接入这头, 所以不能按互联网上的IP包头计算法来算带宽浪费

以下数据,不保证人人都一样,仅仅我抓包的情况

基础数据大小, 信号类型
82 SYN
82 SYN,ACK
74 PSH,ACK PUSH 发送数据 有时基础数据是 82
74 ACK 应答
86 Dup,ACK,
74 FIN,ACK(这个会重复几次确认) 如果强制发送62 RST,ACL关闭连接, 能够省点掉几次来回确认的带宽

这是我在OpenWrt路由器上用tcpdump抓数据分析的, 因为adsl,里面有6个字节PPPOE数据, 头上有本机MAC,和电信MAC(可能是光猫) 浪费了12Byte
不排除,光猫到电信交换机,带宽卡壳点之间,还有其它什么数据浪费

所以,实际 通讯中, 短连接,太浪费基础包,如果每次发16,32Byte之类小包 实际带宽利用率,可能只有 1/100了
应该选择,长连接, 不发数据的话,除了很长时间的Keep包就不会有带宽浪费 (Keep包默认2小时一次, ,网上他们一般改短到20-30分钟一次)

在不重要数据,比如报告客户端是否打开之类的不是特别重要的数据,又不是需要密集发送的,容忍丢包的 可考虑UDP
UDP大小是
50+实体数据, 抓包发现,有时会多点填充的0 比如发8个byte,实际他可能发了16个byte,尾巴上有多出几个0来

**Comment by HeZiHang** [comment]
ugksoft ，你的路由器是家用的还是商用的。路由器要好点的，或者你测试用网线或光纤直连服务端和客户端进行。

**Comment by ugksoft** [comment]
已经确定是Windows引起的, 我中间有一个机子,是vmare over win7的
win7并发限制了, 搞的局域网里每秒并发新建上不去, 慢速连个200万都没问题

这些不算什么技术问题,主要是国内环境非常差,很多东西不能相信标准,甚至不能相信经验
又没有人愿意分享一下遇到坑,最终.....

可以结贴了
