### ISSUE TITLE
超大文件无法下载

### ISSUE THREAD

**Issue by pony5551** [winddriver/Delphi-Cross-Socket#18]
本想测试一下是否支持断点续传，结果放上去一个6GB的iso文件，直接下载不了

**Comment by winddriver** [comment]
CrossHttpServer设计的初衷是用来做REST服务的，没考虑过断点续传下载大文件，以后可以添加

**Comment by pony5551** [comment]
感谢作者回复，从您的代码中感觉到功底的深厚和代码风格的清爽与严谨，能让人学习到很多，谢谢无私奉献！

**Comment by pony5551** [comment]
function TCrossHttpResponse._CheckCompress(ABodySize: Integer): Boolean;
function TCrossHttpResponse._CreateHeader(ABodySize: Integer;
  AChunked: Boolean): TBytes;

好像这两个地方改Int64就可以下载了

**Comment by winddriver** [comment]
感谢反馈，已修正
并且顺便增加了断点续传的支持

**Comment by pony5551** [comment]
TMediaType好像没上传

**Comment by winddriver** [comment]
抱歉，漏掉一个更新，已补上
