### ISSUE TITLE
更新48版本后64位的有问题

### ISSUE THREAD

**Issue by pony5551** [winddriver/Delphi-Cross-Socket#19]
更新48版本后64位的有问题，打不开网页，而且用NativeInt好像没有Int64合适？

**Comment by winddriver** [comment]
已修正。

之所以发送内存块和TBytes相关的方法使用了NativeInt, 是因为动态数组的最大尺寸正好就是NativeInt的最大值
而与流相关的发送方法使用了Int64, 是因为流的Size和Poisition都是Int64

**Comment by pony5551** [comment]
谢谢，受教了
