### ISSUE TITLE
linux 上基本测试不过去

### ISSUE THREAD

**Issue by xalionquan** [winddriver/Delphi-Cross-Socket#2]
在ubuntu 上，用delphi 10.2  编译例子。
用ab 测试，基本上跑不下来。

![qq 20170606173911](https://cloud.githubusercontent.com/assets/17444198/26823438/37f2c272-4ae0-11e7-9f83-3fffc6f19baa.png)

**Comment by winddriver** [comment]
你修改一下Linux最大文件句柄数限制，没记错的话默认只有几百个，你测试没带-k，也就意味着每个请求都会建立连接然后断开连接，socket本质上也是文件句柄，可用的socket基本都还在TIME_WAIT状态没来得及被系统回收，新的请求又不停到来，导致没有可用句柄，从而导致accept失败。

这就是你这现象背后的原因，至于怎么改句柄限制，自行Google一下，每个发行版都不太一样。

发自我的 iPhone

在 2017年6月6日，17:48，xalionquan <notifications@github.com<mailto:notifications@github.com>> 写道：


在ubuntu 上，用delphi 10.2 编译例子。
用ab 测试，基本上跑不下来。

[qq 20170606173911]<https://cloud.githubusercontent.com/assets/17444198/26823438/37f2c272-4ae0-11e7-9f83-3fffc6f19baa.png>

**Comment by xalionquan** [comment]
谢谢，可以跑起来了。
但是老是在最后会退出来。很奇怪。
![qq 20170606215031](https://cloud.githubusercontent.com/assets/17444198/26832736/f995f4ea-4b02-11e7-962e-6ee87951255c.png)
![qq 20170606215634](https://cloud.githubusercontent.com/assets/17444198/26832769/1299ba3a-4b03-11e7-9a0b-414d276eae58.png)

**Comment by winddriver** [comment]
这是1千万次的ab测试，并发1万，服务端是虚拟机中的Ubuntu桌面版
![20170607110011](https://user-images.githubusercontent.com/3221597/26860504-d440e8b2-4b70-11e7-8430-f44fe6f9f832.png)

**Comment by xalionquan** [comment]
好的，我再查一下，谢谢。
