### ISSUE TITLE
服务器关闭时可能的一个问题。

### ISSUE THREAD

**Issue by HeZiHang** [winddriver/Delphi-Cross-Socket#21]
Net.CrossSocket.Base中：
procedure TAbstractCrossSocket.CloseAll;
begin
  CloseAllConnections;
  CloseAllListens;
end;
在执行CloseAllConnections过程中，其他线程可能会接收了新的连接进来，导致CloseAllConnections不能关闭这些新连接，如果先CloseAllListens，是不是可以避免？
是否应该改为：
procedure TAbstractCrossSocket.CloseAll;
begin
  CloseAllListens;
  CloseAllConnections;
end;

**Comment by winddriver** [comment]
嗯，有这个可能。稍后修改
