### ISSUE TITLE
超过64个io线程可能出现的一个问题。

### ISSUE THREAD

**Issue by HeZiHang** [winddriver/Delphi-Cross-Socket#22]
在 Net.CrossSocket.Iocp.pas中：

procedure TIocpCrossSocket.StopLoop;
var
  I: Integer;
begin
  if (FIoThreads = nil) then Exit;

  CloseAll;

  while (ListensCount > 0) or (ConnectionsCount > 0) do Sleep(1);

  for I := 0 to Length(FIoThreads) - 1 do
    PostQueuedCompletionStatus(FIocpHandle, 0, 0, POverlapped(SHUTDOWN_FLAG));
  WaitForMultipleObjects(Length(FIoThreadHandles), Pointer(FIoThreadHandles), True, INFINITE);
  CloseHandle(FIocpHandle);
  for I := 0 to Length(FIoThreads) - 1 do
    FreeAndNil(FIoThreads[I]);
  FIoThreads := nil;
  FIoThreadHandles := nil;
end;

windows的WaitForMultipleObjects好像只能处理64个等待对象，如果线程数量超过64个，可能会有问题。现在或未来会有的计算机的核心数超过64的。
https://msdn.microsoft.com/en-us/library/ms687025(VS.85).aspx

是否可以改为：
procedure TIocpCrossSocket.StopLoop;
var
  I: Integer;
begin
  if (FIoThreads = nil) then Exit;

  CloseAll;

  while (ListensCount > 0) or (ConnectionsCount > 0) do Sleep(1);

  for I := 0 to Length(FIoThreads) - 1 do
    PostQueuedCompletionStatus(FIocpHandle, 0, 0, POverlapped(SHUTDOWN_FLAG));
  for I :=0 to Length(FIoThreads) -1 do
     #WaitForSingleObjects(FIoThreadHandles, INFINITE);  //并不会比Multi多等时间，阻塞在最长时间的Thread后，后面其他线程就直接过。
  CloseHandle(FIocpHandle);
  for I := 0 to Length(FIoThreads) - 1 do
    FreeAndNil(FIoThreads[I]);
  FIoThreads := nil;
  FIoThreadHandles := nil;
end;

**Comment by winddriver** [comment]
有道理，稍后将iocp的StopLoop改成和EPoll、KQueue相同的方式，直接使用线程对象的WaitFor就可以了
