### ISSUE TITLE
能否在ICrossConnection 中 增加 LocalAddr与LocalPort？

### ISSUE THREAD

**Issue by fjfzeagle** [winddriver/Delphi-Cross-Socket#3]
比如我的连接方法是
aClientSocket.Connect('127.0.10.10',8888);
那么LocalAddr应该是127.10.10.1,LocalPort应该是8888(新连接: Connect 127.0.0.1:3431 [at 127.0.10.10:8888])
你的控件支持多端口同时监听，如果没有这两个属性，那么不知道客户是通过哪个端口连接上来的

**Comment by winddriver** [comment]
已增加

**Comment by fjfzeagle** [comment]
非常感谢
