### ISSUE TITLE
HTTP Post提交请求的参数解析不到

### ISSUE THREAD

**Issue by windflee** [winddriver/Delphi-Cross-Socket#30]
HTTP客户端以POST方式提交请求，在服务器端中无法访问，request 的params和query中都没有提交的数据。因此在OnHttpRequest事件中无法处理POST请求。

**Comment by windflee** [comment]
客户端代码是这样的：
procedure TForm1.Button1Click(Sender: TObject);
var s: string;
begin
  Memo1.Lines.Clear;
  Memo1.Lines.Append('aaa=123');
  Memo1.Lines.Append('bbb=456');
  s := IdHTTP1.Post('http://127.0.0.1:8090/nws', Memo1.Lines);
end;

服务端在OnHttpRequest事件中处理请求，代码：
procedure TForm2.OnHttpRequest(Sender: TObject; ARequest: ICrossHttpRequest;
  AResponse: ICrossHttpResponse; var AHandled: Boolean);
begin
  OutputDebugString(pwidechar('aaa: ' + ARequest.Params.Params['aaa']));
  OutputDebugString(pwidechar('aaa: ' + ARequest.Query.Params['aaa']));
  OutputDebugString(pwidechar('bbb: ' + ARequest.Params.Params['bbb']));
  OutputDebugString(pwidechar('bbb: ' + ARequest.Query.Params['bbb']));
  OutputDebugString(pwidechar(ARequest.RawPathAndParams));
end;

输出的结果，请见附件的图片。

![qq 20180730141633](https://user-images.githubusercontent.com/16048114/43380327-55ed41ea-9403-11e8-977e-ba3b30e46280.jpg)

**Comment by windflee** [comment]
谢谢您的回复。想请问一下，为什么ARequest.Params.Params['aaa']是空的？在GET模式下，是可以用ARequest.Query.Params['aaa']来取参数值的，能否在POST模式下，把参数添加到ARequest.Params，这样用起来也更方便。谢谢了！

**Comment by winddriver** [comment]
Params、Query、Body它们的数据来源是不一样的，你看看我代码里这几个属性的注释就明白了
另外也建议简单了解一下HTTP协议
