### ISSUE TITLE
线程问题？

### ISSUE THREAD

**Issue by songshuang8** [winddriver/Delphi-Cross-Socket#31]
参数： 创建线程数=0
测试函数：TCrossHttpResponse.SendFile(const AFileName: string。。
在文件打开成功后，增加Writeln('Create:'+LStream.FileName);
在语句FreeAndNil(LStream)前增加Writeln('Free:'+LStream.FileName);
运行，用于发布一个网页（含有图片，js 等），显示如下：
CrossHttpServer start at port:80, IO threads:9
Press enter stop
Create:E:\Myworker\html\/index.html
Free:E:\Myworker\html\/index.html
Create:E:\Myworker\html\/iamge/ic_launcher.png
Create:E:\Myworker\html\/iamge/ic_launcher.png
Create:E:\Myworker\html\/iamge/guide1.png
Free:E:\Myworker\html\/iamge/guide1.png
Create:E:\Myworker\html\/iamge/guide2.png
Create:E:\Myworker\html\/iamge/guide2.png
Create:E:\Myworker\html\/iamge/guide3.png
Free:E:\Myworker\html\/iamge/guide2.png
Free:E:\Myworker\html\/iamge/guide2.png
Free:E:\Myworker\html\/iamge/guide3.png
Free:E:\Myworker\html\/iamge/guide2.png
Free:E:\Myworker\html\/iamge/guide3.png
Create:E:\Myworker\html\/iamge/guide5.png
Free:E:\Myworker\html\/iamge/guide5.png
Free:E:\Myworker\html\/iamge/ic_launcher.png
Create:E:\Myworker\html\/iamge/guide4.png
Create:E:\Myworker\html\/iamge/guide4.png
Create:E:\Myworker\html\/iamge/guide6.png
Free:E:\Myworker\html\/iamge/guide4.png
Free:E:\Myworker\html\/iamge/guide6.png
感觉线程都乱套了？ 用一个线程时正确的。

**Comment by winddriver** [comment]
多线程是并行执行的，这不是很正常的吗？

发自我的 iPhone

在 2018年8月4日，14:20，songshuang8 <notifications@github.com<mailto:notifications@github.com>> 写道：


参数： 创建线程数=0
测试函数：TCrossHttpResponse.SendFile(const AFileName: string。。
在文件打开成功后，增加Writeln('Create:'+LStream.FileName);
在语句FreeAndNil(LStream)前增加Writeln('Free:'+LStream.FileName);
运行，用于发布一个网页（含有图片，js 等），显示如下：
CrossHttpServer start at port:80, IO threads:9
Press enter stop
Create:E:\Myworker\html/index.html
Free:E:\Myworker\html/index.html
Create:E:\Myworker\html/iamge/ic_launcher.png
Create:E:\Myworker\html/iamge/ic_launcher.png
Create:E:\Myworker\html/iamge/guide1.png
Free:E:\Myworker\html/iamge/guide1.png
Create:E:\Myworker\html/iamge/guide2.png
Create:E:\Myworker\html/iamge/guide2.png
Create:E:\Myworker\html/iamge/guide3.png
Free:E:\Myworker\html/iamge/guide2.png
Free:E:\Myworker\html/iamge/guide2.png
Free:E:\Myworker\html/iamge/guide3.png
Free:E:\Myworker\html/iamge/guide2.png
Free:E:\Myworker\html/iamge/guide3.png
Create:E:\Myworker\html/iamge/guide5.png
Free:E:\Myworker\html/iamge/guide5.png
Free:E:\Myworker\html/iamge/ic_launcher.png
Create:E:\Myworker\html/iamge/guide4.png
Create:E:\Myworker\html/iamge/guide4.png
Create:E:\Myworker\html/iamge/guide6.png
Free:E:\Myworker\html/iamge/guide4.png
Free:E:\Myworker\html/iamge/guide6.png
感觉线程都乱套了？ 用一个线程时正确的。

**Comment by songshuang8** [comment]
不知道是否看懂了，不论怎么样，一个create，必须要有一个free。还有的重复两遍！

**Comment by songshuang8** [comment]
在linux下发现打开刷新一个网页，内存增加异常。才在windows上这样测试的。

**Comment by songshuang8** [comment]
刷新3，4下就增加一个兆内存（把chrome的缓存取消测试的）。windows下内存倒不增加，但跑几天后，dos窗口关闭后，进程关闭不了，必须重启。

**Comment by winddriver** [comment]
能否讲你测试的工程及相关的测试网页和图片打包上来？

**Comment by songshuang8** [comment]
[Delphi-Cross-Socket-master.zip](https://github.com/winddriver/Delphi-Cross-Socket/files/2301603/Delphi-Cross-Socket-master.zip)
整个测试工程及其www文件夹、cross库都在里面。不好意思，这么长时间回复。

**Comment by winddriver** [comment]
![2018-08-20_204334](https://user-images.githubusercontent.com/3221597/44341213-d25cc400-a4b9-11e8-8fe7-42e00f23fa64.png)
这是我用你发的测试工程测试的截图，打开和释放文件都是成对的，没有内存泄漏。
你的Delphi是什么版本？我的开发环境是Delphi 10.2.3，我放一个用ni你上传的工程编译好的程序上来你运行看看。
[test.zip](https://github.com/winddriver/Delphi-Cross-Socket/files/2302403/test.zip)

**Comment by winddriver** [comment]
这个是Linux版
[test-linux.zip](https://github.com/winddriver/Delphi-Cross-Socket/files/2302444/test-linux.zip)
![2018-08-20_210149](https://user-images.githubusercontent.com/3221597/44342100-7fd0d700-a4bc-11e8-83ef-1e32696d5c7c.png)

**Comment by songshuang8** [comment]
![image](https://user-images.githubusercontent.com/16074892/44382004-adae2e00-a545-11e8-9046-3db2e04c79c2.png)
上面是我直接下载运行的结果，我用的是chrome浏览器。出奇的。
线程封装部分我没有大分析。 数据接收http分析及发送部分我理解的多一点。

**Comment by songshuang8** [comment]
我也是d10.2.3
如果是浏览器的问题,但每次出错的文件名称并不相同。

**Comment by songshuang8** [comment]
昨天笔记本烧坏了，今天这次是苹果台式机。 看来是和编译无关，机器无关了。

**Comment by songshuang8** [comment]
我是win7下的，chrome，ie都这样的问题。刚才测试两下，一个是chrome，一个是ie。都是这样子
![image](https://user-images.githubusercontent.com/16074892/44382444-76d91780-a547-11e8-8ca9-87644f5f299e.png)
有时间在win10,ubuntu上再测测
