### ISSUE TITLE
可能存在的一个线程退出问题。

### ISSUE THREAD

**Issue by HeZiHang** [winddriver/Delphi-Cross-Socket#32]
如当前版本下面的程序在退出时，如果StopLoop是被工作线程调用的。可能出现死锁状态。

`procedure TIocpCrossSocket.StopLoop;
var
  I: Integer;
begin
  if (FIoThreads = nil) then Exit;

  CloseAll;

  while (ListensCount > 0) or (ConnectionsCount > 0) do Sleep(1);

  for I := 0 to Length(FIoThreads) - 1 do
    PostQueuedCompletionStatus(FIocpHandle, 0, 0, POverlapped(SHUTDOWN_FLAG));

  CloseHandle(FIocpHandle);

  for I := 0 to Length(FIoThreads) - 1 do
  begin
    FIoThreads[I].WaitFor;
    FreeAndNil(FIoThreads[I]);
  end;
  FIoThreads := nil;
end;
`

建议改为：

`procedure TIocpCrossSocket.StopLoop;
var
  I: Integer;
begin
  if (FIoThreads = nil) then Exit;

  CloseAll;

  while (ListensCount > 0) or (ConnectionsCount > 0) do Sleep(1);

  for I := 0 to Length(FIoThreads) - 1 do
  begin
    FIoThreads[I].Terminate;
    PostQueuedCompletionStatus(FIocpHandle, 0, 0, POverlapped(SHUTDOWN_FLAG));
  end;

  for I := 0 to Length(FIoThreads) - 1 do
  begin
    while not FIoThreads[I].Finished  do
    begin
      if GetCurrentThreadID = MainThreadID then  //由于是通过Synchronize同步到主线程执行，所以调用CheckSynchronize，防止死锁
        CheckSynchronize(0)
      else if GetCurrentThreadID = FIoThreads[I].ThreadID then Break;
      Sleep(1);
    end;
    FreeAndNil(FIoThreads[I]);
  end;
  CloseHandle(FIocpHandle);
  FIoThreads := nil;
end;
`

同理epoll，kqueue

**Comment by HeZiHang** [comment]
比如说，假设做telnet服务器，客户端发送来“shutdown”表示关机或退出命令。服务器收到关机命令后，在工作线程处理关机操作。此时，可能会调用关闭服务器操作。

**Comment by HeZiHang** [comment]
仅供参考
`procedure TIocpCrossSocket.StopLoop;
var
  I: Integer;
  T: TThread;
begin
  if (FIoThreads = nil) then Exit;
  CloseAll;

  while (ListensCount > 0) or (ConnectionsCount > 0) do Sleep(1);

  for I := 0 to Length(FIoThreads) - 1 do
  begin
    FIoThreads[I].Terminate;
    PostQueuedCompletionStatus(FIocpHandle, 0, 0, POverlapped(SHUTDOWN_FLAG));
  end;

  for I := 0 to Length(FIoThreads) - 1 do
  begin
    while not FIoThreads[I].Finished do
    begin
      if GetCurrentThreadID = MainThreadID then 
         CheckSynchronize(0)
      else if GetCurrentThreadID = FIoThreads[I].ThreadID then 
      begin
        T:=FIoThreads[I];
        FIoThreads[I]:=nil;
        TThread.CreateAnonymousThread(
          procedure
          begin
            while not T.Finished do Sleep(1);
            FreeAndNil(T);
          end;
        ).Start;
        Break;
      end;
      Sleep(1);
    end;
    if Assigned(FIOThreads[i]) then FreeAndNil(FIoThreads[I]);
  end;
  CloseHandle(FIocpHandle);
  FIoThreads := nil;
end;`

**Comment by HeZiHang** [comment]
仅供参考
```
procedure TIocpCrossSocket.StopLoop;
var
  I , N: Integer;
  T: TThread;
  P:THandle;
begin
  if (FIoThreads = nil) then Exit;
  CloseAll;

  while (ListensCount > 0) or (ConnectionsCount > 0) do Sleep(1);

  for I := 0 to Length(FIoThreads) - 1 do
  begin
    FIoThreads[I].Terminate;
    PostQueuedCompletionStatus(FIocpHandle, 0, 0, POverlapped(SHUTDOWN_FLAG));
  end;
  N:=Length(TIoThreads);
  for I := 0 to Length(FIoThreads) - 1 do
  begin
    while not FIoThreads[I].Finished do
    begin
      if GetCurrentThreadID = MainThreadID then 
         CheckSynchronize(0)
      else if GetCurrentThreadID = FIoThreads[I].ThreadID then 
      begin
        T:=FIoThreads[I];
        P:=FIocpHandle;
        FIoThreads[I]:=nil;
        TThread.CreateAnonymousThread(
          procedure
          begin
            while not T.Finished do Sleep(1);
            FreeAndNil(T);
            if TInterlocked.Decrement(N)=0 then
                CloseHandle(P);
          end;
        ).Start;
        Break;
      end;
      Sleep(1);
    end;
    if Assigned(FIOThreads[i]) then
    begin
        FreeAndNil(FIoThreads[I]);
        if TInterlocked.Decrement(N)=0 then CloseHandle(FIocpHandle);
     end;
  end;
  FIoThreads := nil;
end;`

**Comment by HeZiHang** [comment]
CloseHandle(FIocpHandle);
需要所有工作线程释放完后再关闭。否则可能会出现FIocpHandle已经关闭了，工作线程中正在处理io

**Comment by winddriver** [comment]
你说这种情况，明显应该收到shutdown之后使用TThread.Queue将StopLoop及关机同步到主线程去执行，而不是直接在工作线程直接执行上述动作。

至于 CloseHandle(FIocpHandle) 放在了所有工作线程结束之前，可能会引起内存泄漏的问题这个我需要找个时间测试一下。

**Comment by HeZiHang** [comment]
我们可以用TThread.queue，用户可能不知道用。可以在也可以在StopLoop中先执行一个Alert，判断GetCurrentThreadID 是否等于MainThreadID，不等于就提示用户。

**Comment by HeZiHang** [comment]
我们可以用TThread.queue，用户可能不知道用。在也可以在StopLoop中先执行一个Alert，判断GetCurrentThreadID 是否等于MainThreadID，不等于就提示用户。

**Comment by winddriver** [comment]
前几天更新了一下，对StopLoop做了一些修改，当在IO工作线程调用会直接抛出异常。
另外把关闭iocp、epoll、kqueue句柄的动作都放到了所有工作线程停止以后，为了实现这个修改，顺便对epoll和kqueue部分代码做了一些调整，详见源码。
