### ISSUE TITLE
建议把openssl替换为mbedtls

### ISSUE THREAD

**Issue by pony5551** [winddriver/Delphi-Cross-Socket#33]
和群友聊天时，群友说openssl有问题已经把你crosssocket的ssl换成了mbedtls

**Comment by edwinyzh** [comment]
请问如何替换？

**Comment by pony5551** [comment]
这个有项目地址，编译一份静态文件，再把ssl相关的代码改成mbedtls的代码处理

**Comment by winddriver** [comment]
这是个不错的建议，OpenSSL坑的确有点多。
不过我实在抽不出太多时间去研究mbedTLS，能否让那位群友将移植的代码贡献出来，我把它整合进去。

**Comment by pony5551** [comment]
我要了mbedTLS的头和相关obj文件上传到https://github.com/pony5551/Delphi-Cross-Socket
了，文件名cross_mbedtls.rar
作者有时间可以看一下

**Comment by winddriver** [comment]
看了下pony5551发上来的代码，感觉要做的工作还不少。
我会抽时间试试将openssl换成mbedtls，不过实在太忙，所以什么时候能完成还无法确定。

**Comment by pony5551** [comment]
貌似我向那位群友要过一次，说是不太愿意公开
，抱歉了

**Comment by winddriver** [comment]
> 貌似我向那位群友要过一次，说是不太愿意公开
> ，抱歉了

要都跟这位群友似的，只知道向别人索取，而不分享，这世界上也就不会有开源这回事了。
我为这位群友的行为深表遗憾，同时也向各位支持DCS框架的朋友表达歉意，我实在太忙，将SSL移植到MbedTLS可能要继续往后推了。

**Comment by pony5551** [comment]
作者有国内的邮箱吗？我发不了gmail

**Comment by pony5551** [comment]
手机发了两个mail

**Comment by winddriver** [comment]
抽时间测试了下pony5511发给我的mbed程序，测试环境为Windows 10 x64，发现并发超过200就会出现连接失败了

这段时间我自己也写了ssl移植到mbed的相关代码，我的代码也只能支持到500并发，超过之后就出现连接失败

然后我测试了mbedtls自带的ssl_server，居然只能支持到10个并发

同样的环境，DCS使用OpenSSL可以轻松跑10000以上的并发

我现在还不是太清楚造成这种情况的原因，稍后我会将我已经写好的dcs带mbedtls的版本放上来，希望大家一起帮我看看，问题出在哪里

**Comment by pony5551** [comment]
可以试试用gcc编译mbed,感觉bcb编译出来可能会有问题

**Comment by pony5551** [comment]
初步测试没发现你说的连接500后失败的问题，但是比openssl效率低很多
openssl可以并发16000,mbed只有5k

**Comment by winddriver** [comment]
我也发现mbedtls的确比openssl效率低很多，google大概搜了一下也发现不少人反应类似的问题，或许有办法进行优化，不过我实在没那么多时间去研究了

**Comment by pony5551** [comment]
效率低的原因是ssl连接太慢,google搜到有人用libuv替换了mbedtls的原有连接！
不过这个太折腾了!
等有时间作者可以用crosssocket替换mbedtls的连接,要么只能等一个openssl的稳定版本试试！

**Comment by winddriver** [comment]
mbedtls慢并不只是因为连接慢，而是它的加解密库就很慢，我这次移植本身就是用的DCS自己的连接，只用了mbedtls的tls握手和加解密而已

**Comment by pony5551** [comment]
不好意思，没认真看代码，那现在mbedtls的慢只有慢慢优化了，不过ab测试时发起1000好像会有一个长时间的等待，估计是连接和握手

**Comment by pony5551** [comment]
看了个贴子，意思好像还是说网络交互对性能影响大一点
https://tls.mbed.org/discussions/generic/performance-of-mbedtls-against-openssl

**Comment by xlnrony** [comment]
谁说我不愿给Net.CrossSslSocket.pas，早发到过ZS,CC,ZE,MH,ZT,ZA群里，你没注意而已
