### ISSUE TITLE
建议调整继承顺序

### ISSUE THREAD

**Issue by xlnrony** [winddriver/Delphi-Cross-Socket#38]
建议继承顺序调整为TCrossData->TAbstractCrossConnection->TCrossConnection->TCrossHttpConnection->TCrossWebSocketConnection—》TCrossMbedTlsConnection/TCrossOpenSSLConnection，目前你这样的继承顺序满足不了，我要ssl和非ssl http Server在一个程序中同时用的状况

**Comment by winddriver** [comment]
这个比较麻烦，不是简单调整一下就能完成的，当然如果你有比较好的实现方式可以共享一下相关代码
