### ISSUE TITLE
large data transfer

### ISSUE THREAD

**Issue by civilian7** [winddriver/Delphi-Cross-Socket#4]
When you exchange and receive data less than 32768 bytes, it works without any problems. However, when transferring data larger than 32768, it sends the size of the stream to the front of the stream, which results in poor data sizing.

**Comment by winddriver** [comment]
upload your code plz

发自我的 iPhone

在 2017年8月31日，16:31，civilian7 <notifications@github.com<mailto:notifications@github.com>> 写道：


When you exchange and receive data less than 32768 bytes, it works without any problems. However, when transferring data larger than 32768, it sends the size of the stream to the front of the stream, which results in poor data sizing.

**Comment by civilian7** [comment]
procedure TPacketSocket.LogicReceived(AConnection: ICrossConnection; ABuf: Pointer; ALen: Integer);
begin
  (AConnection as IPacketConnection).Parse(ABuf, ALen);
end;



procedure TPacketConnection.Parse(ABuf: Pointer; ALen: Integer);
var
  p: PByte;
  r: Integer;
  LSocket: IPacketSocket;
  LPacket: IPacket;
begin
  if (FRecvPacket = nil) then
  begin
    New(FRecvPacket);
    FillChar(FRecvPacket^, SizeOf(TIocpPacket), #0);
  end;

  if (FRecvPacketBytes < SizeOf(TIocpHeader)) then
  begin
    p := @FRecvPacket.Header;
    Inc(p, FRecvPacketBytes);
    r := System.Math.Min(SizeOf(TIocpHeader) - FRecvPacketBytes, ALen);
    Move(ABuf^, p^, r);
    Inc(FRecvPacketBytes, r);

    if (ALen > r) then
    begin
      p := ABuf;
      Inc(p, r);
      Parse(p, ALen - r);
    end;
  end
  else
  begin
    if (FRecvPacket.Data = nil) then
    begin
      try
        GetMem(FRecvPacket.Data, FRecvPacket.Header.DataSize);
      except
        Dispose(FRecvPacket);
        Disconnect;
        Exit;
      end;
    end;

    p := FRecvPacket.Data;
    Inc(p, FRecvPacketBytes - SizeOf(TIocpHeader));
    r := System.Math.Min(ALen, SizeOf(TIocpHeader) + FRecvPacket.Header.DataSize - FRecvPacketBytes);
    Move(ABuf^, p^, r);
    Inc(FRecvPacketBytes, r);

    if (FRecvPacketBytes >= SizeOf(TIocpHeader) + FRecvPacket.Header.DataSize) then
    begin
      LPacket := TPacket.Create(FRecvPacket.Data, FRecvPacket.Header.DataSize);
      (Owner as IPacketSocket).LogicPacketReceived(Self, LPacket);

      FRecvPacketBytes := 0;
      FreeMem(FRecvPacket.Data);
      Dispose(FRecvPacket);
      FRecvPacket := nil;

      if (ALen > r) then
      begin
        p := ABuf;
        Inc(p, r);
        Parse(p, ALen - r);
      end;
    end;
  end;
end;
