### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by robertodellapasqua** [winddriver/Delphi-Cross-Socket#40]
hi Souledge,

thanks for your patience with me,

I have a feature request.

Guess a server with thousands of websocket connections.

Now websocket inherit from httpconnection, so every connection uses a lot of memory (many fields, methods, properties).

My proposal is, after http upgrade 101 websocket established, free the httpconnection interface, leaving only the necessary for the websocket connection.

This will make the websocket server lighter on resources so more scalable.

Thank you.

Roberto

**Comment by winddriver** [comment]
其实 websocket 本身就是基于 http 协议的，在使用 websocket 通讯的过程中，http 协议定义的那些内容也可能会使用到，URL、HEADER 等，这些都是协议的一部分，它们不应该被抛弃掉，可以参考一下其它 websocket 的实现，至少我看过 nodejs 的一些 websocket 库，它们也都将 http 协议相关的数据保留了

我举一个最简单的例子，你可以写一个统一的 websocket 通讯回调函数，在回调函数中通过 Request 的 Method Path 来处理不同的业务逻辑，如果在建立好 websocket 连接之后就将 Method Path 等数据释放了，你就无法做出上述处理了
