### ISSUE TITLE
线程安全问题

### ISSUE THREAD

**Issue by JackTianMY** [winddriver/Delphi-Cross-Socket#42]
您好：
      _HandleRead  这个处理函数，是在线程函数调用的
LRcvd := TSocketAPI.Recv(LConnection.Socket, FRecvBuf[0], RCV_BUF_SIZE);

在处理接受数据是是不是要考虑线程安全。对这方面不太了解。能给我具体说说吗？ 谢谢。

**Comment by winddriver** [comment]
这个接受数据是线程安全的，因为不管是IOCP还是EPOLL、KQUEUE，都能保证在同一时间针对同一个SOCKET只会唤醒一个线程进行IO处理

**Comment by JackTianMY** [comment]
> 这个接受数据是线程安全的，因为不管是IOCP还是EPOLL，KQUEUE，都能保证在同一时间针对同一个插座只会唤醒一个线程进行IO处理
谢谢你的回复： 谢谢你的回复。 我测得情况正如你说的。 但是我不理解的是 如果同一时间这对同意个插座值只处理一个IO处理。 当前处理完成释放后才能处理后续的队列内容。 那要多线程的好处在哪。线程安全我理解了，好想没有利用多线程的好处。 我之前想当然的以为可以同时处理多个io,线程同步需要自己在处理同步机制。

**Comment by JackTianMY** [comment]
> 这个接受数据是线程安全的，因为不管是IOCP还是EPOLL，KQUEUE，都能保证在同一时间针对同一个插座只会唤醒一个线程进行IO处理

这个接受数据是线程安全的，因为不管是IOCP还是EPOLL，KQUEUE，都能保证在同一时间针对同一个插座只会唤醒一个线程进行IO处理
谢谢你的回复：谢谢你的回复。我测得情况正如你说的。但是我不理解的是如果同一时间针对同一个Soket只唤醒一个IO处理。当前处理完成释放后才能处理后续的队列内容。那要多线程的好处在哪。线程安全我理解了，好想没有利用多线程的好处。我之前想当然的以为可以同时处理多个io，线程同步需要自己在处理同步机制。

**Comment by JackTianMY** [comment]
如果不同的

> 这个接受数据是线程安全的，因为不管是IOCP还是EPOLL、KQUEUE，都能保证在同一时间针对同一个SOCKET只会唤醒一个线程进行IO处理

谢谢你的回复。我测得情况正如你说的。但是我不理解的是如果同一时间针对同一个Soket只唤醒一个IO处理。当前处理完成释放后才能处理后续的队列内容。那要多线程的好处在哪。线程安全我理解了，好想没有利用多线程的好处。我之前想当然的以为可以同时处理多个io，线程同步需要自己在处理同步机制。

**Comment by winddriver** [comment]
多线程的好处当然是处理多个连接

发自我的 iPhone

在 2019年2月24日，23:39，JackTianMY <notifications@github.com<mailto:notifications@github.com>> 写道：


这个接受数据是线程安全的，因为不管是IOCP还是EPOLL，KQUEUE，都能保证在同一时间针对同一个插座只会唤醒一个线程进行IO处理
谢谢你的回复： 谢谢你的回复。 我测得情况正如你说的。 但是我不理解的是 如果同一时间这对同意个插座值只处理一个IO处理。 当前处理完成释放后才能处理后续的队列内容。 那要多线程的好处在哪。线程安全我理解了，好想没有利用多线程的好处。 我之前想当然的以为可以同时处理多个io,线程同步需要自己在处理同步机制。

**Comment by JackTianMY** [comment]
在 ProcessIoEvent
 这个多线程 的函数体内
if not GetQueuedCompletionStatus(FIocpHandle, LBytes, ULONG_PTR(LSocket), POverlapped(LPerIoData), INFINITE) then

是不是 同一时刻来的 不同的soket 的 io  可以 两个 线程同时处理。

**Comment by JackTianMY** [comment]
如果可以同时并不处理不同soket 的io  那 比如 接收数据    TriggerReceived(LConnection, @FRecvBuf[0], LRcvd);  这个 FRecvBuf[0], 是不是 就不安全。 我理解的好想不对 。

**Comment by pony5551** [comment]
> 如果可以同时并不处理不同soket 的io 那 比如 接收数据 TriggerReceived(LConnection, @FRecvBuf[0], LRcvd); 这个 FRecvBuf[0], 是不是 就不安全。 我理解的好想不对 。


我觉得你需要补一个多线程基础，呵呵

**Comment by JackTianMY** [comment]
如果不同的soket的io 可以让工作线程 并行处理，比如接受数据。那 TriggerReceived(LConnection, @FRecvBuf[0], LRcvd); 对于FRecvBuf[0] 是不是不安全

**Comment by JackTianMY** [comment]
> > 如果可以同时并不处理不同soket 的io 那 比如 接收数据 TriggerReceived(LConnection, @FRecvBuf[0], LRcvd); 这个 FRecvBuf[0], 是不是 就不安全。 我理解的好想不对 。
> 
> 我觉得你需要补一个多线程基础，呵呵

我之前是做工业串口通讯的。多线程一直在用。 就是不太理解iocp的机制

**Comment by JackTianMY** [comment]
TAbstractCrossSocket = class abstract(TInterfacedObject, ICrossSocket)
  protected const
    RCV_BUF_SIZE = 32768;
  protected class threadvar
    FRecvBuf: array [0..RCV_BUF_SIZE-1] of Byte;   。。。。。。

接受缓冲区是在这里定义的，线程函数都用到这个 变量了。但是没有做同步处理。

**Comment by JackTianMY** [comment]
如果  GetQueuedCompletionStatus 这个 函数 对所有的 线程都是互斥的（只能唤醒一个挂起线程）那 就是安全的。 但是  这样 我就得 多线程好想没有用上

**Comment by JackTianMY** [comment]
** [winddriver](/winddriver) **  我是不是可以这样理解。 不同的soket io 同一时间来了。 GetQueuedCompletionStatus  只能唤醒一个 i 操作， 其他线程只是在哪随时待命。同一时刻 对 io 的操作对外来说是单线程的。  多线程 只对 GetQueuedCompletionStatus 它的调度起作用。加快调度。

**Comment by pony5551** [comment]
看msdn文档吧

**Comment by JackTianMY** [comment]
> 看MSDN文档吧

好的

**Comment by JackTianMY** [comment]
In the previous example, the extra threads appear to be useless and never run, but that assumes that the running thread never gets put in a wait state by some other mechanism, terminates, or otherwise closes its associated I/O completion port. Consider all such thread execution ramifications when designing the application.

**Comment by winddriver** [comment]
不对，不同的socket io如果同一时间到达，是会同时唤醒不同的线程同时处理的

发自我的 iPhone

在 2019年2月25日，00:24，pony5551 <notifications@github.com<mailto:notifications@github.com>> 写道：


看msdn文档吧

**Comment by JackTianMY** [comment]
我上面那个回复是MSDN里的截断。只是一片段。我理解不同soket 同时到达 如果等待线程足够用的话会有并发操作，基于这一点我才有线程安全的疑问。因为 FRecvBuf: array [0..RCV_BUF_SIZE-1] of Byte; 这个数组 并发操作的化 会多个线程共享使用。在线程里使用 这个数组是不是会造成 不完全。

**Comment by viniciusfbb** [comment]
@JackTianMY The array FRecvBuf is not shared by multiple threads, it is a threadvar, i.e, each thread will have a individual variable of it.

**Comment by winddriver** [comment]
楼上的朋友已经帮我回答了，threadvar是每个线程独立的，不会有线程安全的问题，这是delphi很基础的东西，可能你没太注意

**Comment by JackTianMY** [comment]
嗯  protected class threadvar 没注意前面这个关键字。 谢谢 大家的帮助解除一直困扰我的问题。
