### ISSUE TITLE
我有个疑问，weak和unsafe与内存泄漏

### ISSUE THREAD

**Issue by pony5551** [winddriver/Delphi-Cross-Socket#45]
把所有weak替换为unsafe检测无泄漏，但用weak则有泄漏
我用fastmm4 release 4992检测的

**Comment by pony5551** [comment]
使用weak时跟踪到会有两次释放接口！泄漏原因可能就在这里

**Comment by winddriver** [comment]
我刚刚测试了下，把weak替换成unsafe，果然什么问题都没了！
测试了最新版FastMM4、IntelTBB、BrainMM、ScaleMM2、RDPHeap64，统统都没问题！

看来这就是[weak]的内部实现无法很好的跟第三方内存管理库配合引起的了。

稍后我就将代码更新上来
