### ISSUE TITLE
close和callback顺序问题！

### ISSUE THREAD

**Issue by pony5551** [winddriver/Delphi-Cross-Socket#49]
感觉把close放到callback后面靠谱点，现在这样callnack传递的对象好像意义不大，另外zs群主说异步发送有时不返回，具体情况不清楚

**Comment by winddriver** [comment]
的确是这样，已调整

**Comment by pony5551** [comment]
还有Net.CrossSocket.Iocp
266行
490行
611行
659行

**Comment by pony5551** [comment]
666行建议一起按这个顺序来

**Comment by pony5551** [comment]
epoll和Kqueue应该也有类似的

**Comment by pony5551** [comment]
https://github.com/pony5551/Delphi-Cross-Socket
这里我改了3个文件，Souledge可以看看是不是正确

**Comment by pony5551** [comment]
好像改过后，程序退出时不会卡顿！
之前程序退出，或多或少有时会卡顿

**Comment by winddriver** [comment]
已修改
