### ISSUE TITLE
重构版本的Linux下Net.Posix.inc文件不存在

### ISSUE THREAD

**Issue by bamlan** [winddriver/Delphi-Cross-Socket#5]
建立一个空的Net.Posix.inc后，修改Net.CrossSocket.Epoll单元的TEpollCrossSocket._HandleWrite方法542行PosixSend为TSocketAPI.Send（报PosixSend函数未定义）：
    `// 发送数据`
    `//LSent := PosixSend(LConnection.Socket, LSendItem.Data, LSendItem.Size);`
    `LSent := TSocketAPI.Send(LConnection.Socket, LSendItem.Data, LSendItem.Size);`
可以通过编译，但测试在Linux（Ubuntu17.04 Server+Delphi10.2）下工作不正常！

**Comment by winddriver** [comment]
抱歉，提交的时候漏掉了个，已经补上
