### ISSUE TITLE
Accessviolation on Linux with TEpollCrossSocket.Send in Net.CrossSocket.Epoll.pas

### ISSUE THREAD

**Issue by mcvanderkooij** [winddriver/Delphi-Cross-Socket#55]
after GetMem we need to fill the memory with zero's. Now the reference to the callback is not zero and it is trying to decrease the refcount to the interface in the callback member. 

procedure TEpollCrossSocket.Send(AConnection: ICrossConnection; ABuf: Pointer;
  ALen: Integer; const ACallback: TProc<ICrossConnection, Boolean>);
var
  LEpConnection: TEpollConnection;
  LSendItem: PSendItem;
begin
  // 测试过先发送, 然后将剩余部分放入发送队列的做法
  // 发现会引起内存访问异常, 放到队列里到IO线程中发送则不会有问题
  {$region '放入发送队列'}
  GetMem(LSendItem, SizeOf(TSendItem));
  **FillChar(LSendItem^, SizeOf(TSendItem), 0);**
  LSendItem.Data := ABuf;
  LSendItem.Size := ALen;
  LSendItem.Callback := ACallback;

  LEpConnection := AConnection as TEpollConnection;

  LEpConnection._Lock;
  try
    // 将数据放入队列
    LEpConnection.FSendQueue.Add(LSendItem);

    // 由于epoll队列中每个套接字只有一条记录, 为了避免监视发送数据的时候
    // 无法接收数据, 这里必须同时监视读和写
    if not LEpConnection._WriteEnabled then
      LEpConnection._UpdateIoEvent([ieRead, ieWrite]);
  finally
    LEpConnection._Unlock;
  end;
  {$endregion}
end;

**Comment by mcvanderkooij** [comment]
The same applies to TKqueueCrossSocket.Send in Net.CrossSocket.Kqueue.pas

I have checked other GetMem calls, they are ok

**Comment by robertodellapasqua** [comment]
epoll layer should be rewritten, actually has troubles with high loads (failed requests, slow throughput)
when I have time will try to do a new version

**Comment by winddriver** [comment]
It is true that the newly allocated memory is probably not 0, which will cause the following assignment to be incorrectly executed _Release. Thank you.

At the same time, I am also looking forward to the improved version of robertodellapasqua. I don't have much energy and time to do this, and I am counting on you.

**Comment by RoLex** [comment]
@mcvanderkooij 

Could you please provide example of `LEpConnection._WriteEnabled` implementation in your example?

I'm currently suffering with EPOLL writing out of order when used with OpenSSL.
