### ISSUE TITLE
iocp 单元有一处存在泄漏风险

### ISSUE THREAD

**Issue by pony5551** [winddriver/Delphi-Cross-Socket#56]
if Assigned(LPerIoData.Callback)
            and (LPerIoData.CrossData is TIocpConnection) then
            LPerIoData.Callback(LPerIoData.CrossData as ICrossConnection, False);

          LPerIoData.CrossData.Close; //这里可能会释放被closeall释放的对象！用日志输出每个close处的对象，发现的

**Comment by pony5551** [comment]
感觉那个closeall应该全包在锁内

**Comment by viniciusfbb** [comment]
@pony5551 Test with this https://github.com/viniciusfbb/Delphi-Cross-Socket/blob/master/Net/Net.CrossSocket.Iocp.pas
There was some leaks that I solved. Using it I could not identify any more leak.

**Comment by winddriver** [comment]
我觉得你真应该好好想想我为什么坚持要用接口而不用TObject，等你想通了你就不会提这个问题了

发自我的 iPhone

在 2019年2月22日，14:50，pony5551 <notifications@github.com<mailto:notifications@github.com>> 写道：


      if Assigned(LPerIoData.Callback)
        and (LPerIoData.CrossData is TIocpConnection) then
        LPerIoData.Callback(LPerIoData.CrossData as ICrossConnection, False);

      LPerIoData.CrossData.Close; //这里可能会释放被closeall释放的对象！用日志输出每个close处的对象，发现的

**Comment by pony5551** [comment]
确实用接口这个问题可以避免，但好像有时会发生

**Comment by robertodellapasqua** [comment]
sorry if I'm nasty, indeed also with interfaces as now, we get 100k operations/sec on a single I7, it's a monster considering that old approach with Indy or ICS (that both are excellent) we will get 1000 ops/sec.
So the bottleneck is not here, we can use interfaces as now.
I'm solving zlib compression patching, then will do transmitfile, we will have an exceptional server.
Later if I have time will redo together with you epoll (also there we can investigate to use libaio for files)

**Comment by pony5551** [comment]
> @pony5551 Test with this https://github.com/viniciusfbb/Delphi-Cross-Socket/blob/master/Net/Net.CrossSocket.Iocp.pas
> There was some leaks that I solved. Using it I could not identify any more leak.

thanks

**Comment by robertodellapasqua** [comment]
so please let us know when Souledge has merged all those new changes, so I'll update code base, thanks

**Comment by pony5551** [comment]
谢谢 robertodellapasqua 所做的努力！

**Comment by robertodellapasqua** [comment]
MM is the best out there industry proven foundation Intel, SIMD IPP also. It's a good combo, and the powerful and stable layer for server apps. Tomorrow send you the ZLib accelerator.
1MB text
SystemZlib 1800msec zcfastest
SeaZlib 500msec
I have studied dozen publications about Mem managers and did this choice, Linux world tend to use cloufflare fork sse4.2, but our SeaZlib Intel engineered is fasteer and reliable. 
Really the best of the best MEMMAN, RTLsubset, HTTPdeflate to fire Delphi app up to the stars!!!
