### ISSUE TITLE
Unexpected _HandleRead parameter

### ISSUE THREAD

**Issue by viniciusfbb** [winddriver/Delphi-Cross-Socket#61]
![image](https://user-images.githubusercontent.com/11139086/53918515-e75c0780-4045-11e9-9e4d-10efcd9e500a.png)

In some cases, though rare, _HandleRead is called with the APerIoData.CrossData nil. I don't know because it occurs and the best solution, but I believe that just a simple check could avoid this:

```
  LConnection := APerIoData.CrossData as ICrossConnection;
  if not Assigned(LConnection) then
    Exit;
```

**Comment by winddriver** [comment]
fixed

**Comment by viniciusfbb** [comment]
Thank you! :)
