### ISSUE TITLE
建议给线程加上初始化与结束事件!

### ISSUE THREAD

**Issue by pony5551** [winddriver/Delphi-Cross-Socket#62]
![QQ图片20190315072714](https://user-images.githubusercontent.com/36391163/54398120-d1101480-46f3-11e9-8f66-85da1103ecfa.png)
谢谢！
这样可以在线程进入循环前加一些初始化业务的动作！不会影响框架性能！谢谢！

**Comment by winddriver** [comment]
已增加

**Comment by pony5551** [comment]
谢谢！
