### ISSUE TITLE
反馈一个 HTTP 发送文件的小BUG

### ISSUE THREAD

**Issue by gtyhn** [winddriver/Delphi-Cross-Socket#71]
在 Net.CrossHttpServer 中的 TCrossHttpResponse.SendFile 方法里，打开读取流操作原始代码为：

LStream := TFileStream.Create(AFileName, fmOpenRead, fmShareDenyNone);

实际应该修改为：

LStream := TFileStream.Create(AFileName, fmOpenRead or fmShareDenyNone);

本人当前测试环境，win7-delphi 10.3.2，此问题在测试并发同一个文件传输时，会出现“另一个程序正在使用此文件,进程无法访问”异常，进入 System.SysUtils 单元查看 FileCreate 时，发现第三个参数在 windows 平台没有被使用。

**Comment by winddriver** [comment]
感谢反馈，的确有这个问题，已修正
