### ISSUE TITLE
压缩传输无效！

### ISSUE THREAD

**Issue by pony5551** [winddriver/Delphi-Cross-Socket#75]
参数这样设置
  
FServer.Compressible := True;
  FServer.MinCompressSize := 0; 

使用CrossWebSocketServer测试时发现，不管是静态文件还是，向client发送bytes和流，都不会压缩
测试是使用
procedure Send(const ABody: TBytes; ACallback: TProc<ICrossConnection, Boolean> = nil); overload;

Content-Type: text/html

请验证，谢谢

**Comment by pony5551** [comment]
AResponse.SendZCompress(LBytes[0], Length(LBytes), ctGZip);这样使用也无效

**Comment by winddriver** [comment]
你检查一下前端请求的时候accept-encoding是不是没传gzip或deflate，这个压缩肯定没问题，公司的业务系统一直在用

发自我的iPhone

在 2020年3月29日，15:50，pony5551 <notifications@github.com> 写道：

﻿

参数这样设置

FServer.Compressible := True;
FServer.MinCompressSize := 0;

使用CrossWebSocketServer测试时发现，不管是静态文件还是，向client发送bytes和流，都不会压缩
测试是使用
procedure Send(const ABody: TBytes; ACallback: TProc<ICrossConnection, Boolean> = nil); overload;

Content-Type: text/html

请验证，谢谢

**Comment by pony5551** [comment]
前端加了gzip的，而且浏览器也测试过，websocket的几个文件都不会压缩
Accept-Encoding: gzip, deflate, br
Accept-Encoding: gzip都试过

**Comment by winddriver** [comment]
websocket不支持压缩

发自我的iPhone

在 2020年3月29日，16:47，pony5551 <notifications@github.com> 写道：

﻿

前端加了gzip的，而且浏览器也测试过，websocket的几个文件都不会压缩
Accept-Encoding: gzip, deflate, br
Accept-Encoding: gzip都试过

**Comment by pony5551** [comment]
抱歉，我自己的问题,抓包工具把浏览器的gzip, deflate干掉了，这样服务器就不压缩了
谢谢
