### ISSUE TITLE
一点点的优化建议

### ISSUE THREAD

**Issue by gtyhn** [winddriver/Delphi-Cross-Socket#78]
### 1、inline 问题

这个问题主要与delphi编译器有关，如果函数返回值为 string 或一些管理类型时，在 delphi 10.2 或之后的版本生成的机器码非常垃圾，比如以下示例代码：

function test: string; inline;
begin
  Result := 'hello world';
end;

var str := test; // 此处下断点观察汇编码

可以自行反编译看看，建议库中带有自管理类型的返回函数在使用delphi 10.2 或之后的版本 inline 时慎用。

### 2、TProc 等匿名方法参数

在库中有很多以匿名方法作为回调参数使用，比如 Net.CrossHttpServer 中的 Send、SendNoCompress、SendZCompress 之类的，建议 ACallback 加入 const 关键字，该参数实际上作为接口在传递，再加上 delphi 的编译器问题，会产生很多不必要的参数接口引用代码。

### 3、老生常谈的接口参数

之前也有反应过将接口作为参数时在前面加入 const 以防止方法内部产生不必要的接口引用代码，作者的意思是故意这样设计的，其实完全没必要，接口跟 string 这种类型参数在delphi内部自动管理方式一样，不会因为不加 const 就不会产生内存泄漏，该产生的还是会产生，我这边将所有接口参数加上 const 后压力测试并发没有任何内存泄漏或异常地址，所以我这边每次在作者更新后都得把所有以接口作为参数的前面加入 const，非常不方便。

最后还是很感谢作者提供这么优秀的delphi跨平台网络库，算是中国搞delphi界的一股清流，不像一些人在网上抄一些代码封装成这个中间件那个中间件拿去卖钱的，这样搞下去只会让国内搞delphi的路越走越窄，花钱买他们这些中间件，用 go 或 node.js 不香吗？不好意思，结尾处随便吐了个槽。

**Comment by winddriver** [comment]
感谢反馈，尽快改进！

发自我的iPhone

在 2020年5月6日，19:14，gtyhn <notifications@github.com> 写道：

﻿

1、inline 问题

这个问题主要与delphi编译器有关，如果方法返回值为 string 或一些管理类型时，在 delphi 10.2 或之后的版本生成的机器码非常垃圾，比如以下示例代码：

`function test: string; inline;
begin
Result := 'hello world';
end;

var str := test; // 此处下断点观察汇编码
`

可以自行反编译看看，建议库中带有自管理类型的返回方法在使用delphi 10.2 或之后的版本 inline 时慎用。

2、TProc 等匿名方法参数

在库中有很多以匿名方法作为回调参数使用，比如 Net.CrossHttpServer 中的 Send、SendNoCompress、SendZCompress 之类的，建议 ACallback 加入 const 关键字，该参数实际上作为接口在传递，再加上 delphi 的编译器问题，会产生很多不必要的参数接口引用代码。

3、老生常谈的接口参数

之前也有反应过将接口作为参数时在前面加入 const 以防止方法内部产生不必要的接口引用代码，作者的意思是故意这样设计的，其实完全没必要，接口跟 string 这种类型参数在delphi内部自动管理方式一样，不会因为不加 const 就不会产生内存泄漏，该产生的还是会产生，我这边将所有接口参数加上 const 后压力测试并发没有任何内存泄漏或异常地址，所以我这边每次在作者更新后都得把所有以接口作为参数的前面加入 const，非常不方便。

最后还是很感谢作者提供这么优秀的delphi跨平台网络库，算是中国搞delphi界的一股清流，不像一些人在网上抄一些代码封装成这个中间件那个中间件拿去卖钱的，这样搞下去只会让国内搞delphi的路越走越窄，花钱买他们这些中间件，用 go 或 node.js 不香吗？不好意思，结尾处随便吐了个槽。
