### ISSUE TITLE
Net.CrossHttpServer 的一些优化

### ISSUE THREAD

**Issue by gtyhn** [winddriver/Delphi-Cross-Socket#81]
TCrossHttpConnection.Create 中不需要特别声明一个 LConnection: ICrossHttpConnection 作引用计数，直接改成以下即可：

constructor TCrossHttpConnection.Create(const AOwner: ICrossSocket;
  const AClientSocket: THandle; const AConnectType: TConnectType);
begin
  inherited;

  FRequest := TCrossHttpRequest.Create(Self);
  FResponse := TCrossHttpResponse.Create(Self);
end;

然后 TCrossHttpRequest.Create、TCrossHttpResponse.Create、TCrossHttpRouter.Create 的参数加入 const 减少接口引用计数。

以上修改在我这边已经过并发压力测试

**Comment by viniciusfbb** [comment]
True, in Create the refcount of the class is 1.

**Comment by winddriver** [comment]
感谢反馈，已做调整
