### ISSUE TITLE
[dcc64 Warning] Net.CrossServer.pas(53): W1010 Method 'Create' hides virtual method of base type 'TCrossSslServer'

### ISSUE THREAD

**Issue by newzyt** [winddriver/Delphi-Cross-Socket#85]
unit Net.CrossSslServer;
 TCrossSslServer = class(TCrossSslSocket, ICrossSslServer)
  private
    FPort: Word;
    FAddr: string;
    FStarted: Integer;
    function GetAddr: string;
    function GetPort: Word;
    function GetActive: Boolean;
    procedure SetAddr(const Value: string);
    procedure SetPort(const Value: Word);
    procedure SetActive(const Value: Boolean);
  public

    constructor Create(const AIoThreads: Integer); overload;override;

**Comment by winddriver** [comment]
Corrected
