### ISSUE TITLE
一个http处理的潜在问题DoOnRequest中

### ISSUE THREAD

**Issue by pony5551** [winddriver/Delphi-Cross-Socket#89]
![QQ图片20200919174222](https://user-images.githubusercontent.com/36391163/93664165-80733780-fa9f-11ea-8b05-b9e8b1407d3f.png)
上图中，断点在进入方法时LHandled的默认值是True,一般情况下是False

这里我这台机器有个项目默认就是True,这样会导致请求一个不存在的地址时处理线程会被卡住，http服务不返回

是不是LHandled应该给一个初始值？

LHandled := False;

**Comment by pony5551** [comment]
我自己已经加上初始值了

**Comment by winddriver** [comment]
确实有这个可能，局部变量的初始值是随机的，感谢反馈，已修正
